# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Clnt

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Clients(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Clients()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClients(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Clients
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Clients
    def Clients(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Clnt.Client import Client
            obj = Client()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Clients
    def ClientsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Clients
    def ClientsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ClientsStart(builder):
    builder.StartObject(1)

def Start(builder):
    ClientsStart(builder)

def ClientsAddClients(builder, clients):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clients), 0)

def AddClients(builder, clients):
    ClientsAddClients(builder, clients)

def ClientsStartClientsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartClientsVector(builder, numElems: int) -> int:
    return ClientsStartClientsVector(builder, numElems)

def ClientsEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClientsEnd(builder)
