# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Clnt

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Person(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Person()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPerson(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Person
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Person
    def Age(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # Person
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Person
    def Gender(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def PersonStart(builder):
    builder.StartObject(3)

def Start(builder):
    PersonStart(builder)

def PersonAddAge(builder, age):
    builder.PrependInt16Slot(0, age, 0)

def AddAge(builder, age):
    PersonAddAge(builder, age)

def PersonAddWeight(builder, weight):
    builder.PrependFloat32Slot(1, weight, 0.0)

def AddWeight(builder, weight):
    PersonAddWeight(builder, weight)

def PersonAddGender(builder, gender):
    builder.PrependBoolSlot(2, gender, 0)

def AddGender(builder, gender):
    PersonAddGender(builder, gender)

def PersonEnd(builder):
    return builder.EndObject()

def End(builder):
    return PersonEnd(builder)
